### ISSUE TITLE
Epic 2: Integrate Code with App

### ISSUE THREAD

**Issue by jacobhillock** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#41]
As a user, I would like to be able to see the dog highlighted in a given image so that I can know where the dog is in the image.
   - [x] Completing the prototype
   - [x] Decide on server - Baylie, Karen, & Jacob
   - [x] Research how to integrate the server - Baylie & Karen (Oct 12) issue #55 
   - [x] Upload and integrate App to the cloud issue #58 - This issue was closed due to similarity to #60 
   - [x] AWS App integreation #60

**Comment by sjiang1** [comment]
Checked the tasks. All look good.

**Comment by sjiang1** [comment]
@cflones 
I don't find any of your tasks labeled with due dates. Please label your tasks with due dates.
