### ISSUE TITLE
Epic 1: Display Dog Breed 

### ISSUE THREAD

**Issue by jacobhillock** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#42]
As a user, I would like to be able to see a box that can show a dog breed so that I can know where the output will be.
- [x] issue #51 
- [x] issue #52
- [x] issue #57
- [x] issue #69 - Implement UI design features
- [x] issue #81 optimizing
- [x] issue #85 new solution with ImageAI
- [x] issue #88 new model without ImageAI
- [x] issue #94 mix breed dog

**Comment by sjiang1** [comment]
Please add a short description for each task.
