### ISSUE TITLE
Epic 4: Using the cloud

### ISSUE THREAD

**Issue by jacobhillock** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#44]
As a user, I would like the processing to be handled off my phone because my phone is not that powerful.

- [x] Find a cloud service - Bayle, Karen, & Jacob - issue #50 
- [x] Obtain Models - Jacob & Yao - issue #56
- [x] Upload Code - Jacob & Yao - issue #53
- [x] Upload Model - Jacob & Yao - issue #54
- [x] AWS App Integration - issue #60
- [x] AWS Development - Jacob, Yao, Baylie, Karen, Cassie issue #66

**Comment by sjiang1** [comment]
Is it related to Epic 2: Integrate Code with App #41? What's the difference between these two epics?

**Comment by sjiang1** [comment]
Why is "Obtain Models" related to "using the cloud"?
